definitions:
  api.GetResponse:
    properties:
      last_sync:
        type: string
      value:
        type: integer
    type: object
  api.SetRequest:
    properties:
      value:
        type: integer
    required:
    - value
    type: object
info:
  contact: {}
paths:
  /storage:
    get:
      consumes:
      - application/json
      description: Get the current value of the storage
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.GetResponse'
        "500":
          description: Internal Server Error
          schema:
            properties:
              error:
                type: string
            type: object
      summary: Get Storage Value
      tags:
      - Storage
    put:
      consumes:
      - application/json
      description: Set a new value for the storage
      parameters:
      - description: Storage
        in: body
        name: Storage
        required: true
        schema:
          $ref: '#/definitions/api.SetRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Ok
          schema:
            properties:
              message:
                type: string
            type: object
        "400":
          description: Bad Request
          schema:
            properties:
              error:
                type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            properties:
              error:
                type: string
            type: object
      summary: Set Storage Value
      tags:
      - Storage
swagger: "2.0"
